In [1]:
import numpy as np
vec1 = np.array([1,2,3,4])

print(vec1.dot(np.transpose(vec1)))

30


In [14]:
vec2 = np.random.random((4,5))
print(vec2)
print()
print(np.argmax(vec2))

[[0.24273608 0.98986573 0.08525235 0.79368841 0.84963422]
 [0.92586704 0.72880409 0.94888061 0.03560561 0.25952191]
 [0.80568963 0.42740875 0.93090018 0.95601005 0.42477948]
 [0.80974697 0.76957984 0.74471281 0.19830202 0.50752429]]

1


In [15]:
import numpy as np
v1=np.array([1,2])
v2=np.array([3,4])
v3=np.array([5,6])
v4=np.column_stack([v1,v2,v3])
print(v4)

[[1 3 5]
 [2 4 6]]


In [61]:
import itertools as it
import numpy as np

def get_combinations(X,r):
    return it.combinations_with_replacement(X,r)

def poly_trans(X,degree):
    length = len(X)
    X = np.transpose(X)
    result = np.ones(length)
    for r in range(1,degree+1):
        possible_combinations = get_combinations(X,r)

        for combination in possible_combinations:
            combination, x_appended= np.array([combination[0]]), np.ones(length)

            for col in combination:
                x_appended = x_appended * col
            result = np.column_stack([result,x_appended])
    
    return result
X = np.array([[1,8],[5,2],[2,0]])
poly_trans(X,2)

array([[1., 1., 8., 1., 1., 8.],
       [1., 5., 2., 5., 5., 2.],
       [1., 2., 0., 2., 2., 0.]])

In [8]:
import numpy as np
a = np.array([-11,12,-3,4])
np.sum(np.abs(a))

30